/**
 * i18n configuration shared by server and client.
 *
 * The app is bilingual: Albanian (default, for our Kosovo SME audience) and
 * English. English is the *source* language authored by developers in
 * `messages/en.json`; Albanian (`messages/sq.json`) is generated by the
 * `scripts/i18n-translate.mjs` tool so the two catalogs stay in sync.
 */

export const LOCALES = ["sq", "en"] as const;
export type Locale = (typeof LOCALES)[number];

export const DEFAULT_LOCALE: Locale = "sq";

/** Non-HttpOnly so the locale switcher can read/set it client-side too. */
export const LOCALE_COOKIE = "lifa_locale";

/** Human labels for the switcher (each shown in its own language). */
export const LOCALE_LABELS: Record<Locale, string> = {
  sq: "Shqip",
  en: "English",
};

/** Maps an app locale to a BCP-47 tag for Intl number/date formatting. */
export const INTL_LOCALE: Record<Locale, string> = {
  sq: "sq-AL",
  en: "en-US",
};

export function isLocale(value: unknown): value is Locale {
  return typeof value === "string" && (LOCALES as readonly string[]).includes(value);
}

export function normalizeLocale(value: unknown): Locale {
  return isLocale(value) ? value : DEFAULT_LOCALE;
}
